#pragma kernel CSMain

RWTexture3D<float4> Result;
int Resolution;
float Scale;
float ErosionScale;

float3 Hash33(float3 p) {
    p = float3(dot(p, float3(127.1, 311.7, 74.7)),
               dot(p, float3(269.5, 183.3, 246.1)),
               dot(p, float3(113.5, 271.9, 124.6)));
    return frac(sin(p) * 43758.5453123);
}

// https://iquilezles.org/articles/voronoilines/
float3 Voronoi(float3 x, float scale) {
    x *= scale;
    float3 p = floor(x);
    float3 f = frac(x);

    float3 res = scale.xxx;
    for (int k = -1; k <= 1; k++)
        for (int j = -1; j <= 1; j++)
            for (int i = -1; i <= 1; i++) {
                float3 b = float3(i, j, k);
                int3 cell = ((int3(p) + int3(b)) % scale + scale) % scale;
                float3 r = b - f + Hash33(cell);
                float d = dot(r, r);

                if (d < res.x) {
                    res.z = res.y;
                    res.y = res.x;
                    res.x = d;
                }
                else if (d < res.y) {
                    res.z = res.y;
                    res.y = d;
                } else if (d < res.z) {
                    res.z = d;
                }
            }

    return sqrt(res);
}

// https://iquilezles.org/articles/fbm/
float3 fbmOneMinusVoronoi(float3 x, float H, int numOctaves, float scale) {
    float G = exp2(-H);
    float f = 1.0;
    float a = 1.0;
    float3 t = 0.0;
    for(int i = 0; i < numOctaves; i++)
    {
        t += a * (1 - Voronoi(f*x, scale));
        f *= 2.0;
        a *= G;
    }
    return t;
}

float3 fbmVoronoi(float3 x, float H, int numOctaves, float scale) {
    float G = exp2(-H);
    float f = 1.0;
    float a = 1.0;
    float3 t = 0.0;
    for(int i = 0; i < numOctaves; i++)
    {
        t += a * Voronoi(f*x, scale);
        f *= 2.0;
        a *= G;
    }
    return t;
}

[numthreads(8, 8, 8)]
void CSMain(uint3 id : SV_DispatchThreadID) {
    if (Resolution < 0)
        return;

    uint resolution = Resolution;
    if (id.x >= resolution || id.y >= resolution || id.z >= resolution)
        return;

    float3 pos = (float3)id / (float)Resolution;
    
    float r = fbmOneMinusVoronoi(pos, 1, 2, Scale).x;
    float g = fbmVoronoi(pos, 1, 4, ErosionScale).x;
    float b = 0;
    float a = 1;

    Result[id] = float4(r, g, b, a);
}
