Shader "Custom/VolumetricSmoke"
{
    Properties
    {
        [Header(Smoke Properties)]
        _MainColor ("Smoke Color", Color) = (1, 1, 1, 1)
        _WindDirection ("Wind Direction", Vector) = (0, -3, 1, 0)

        [Header(Raymarching Settings)]
        _StepSize ("Step Size", Range(0.01, 0.2)) = 0.01
        _ShadowStepSize ("Shadow Step Size", Range(0.01, 0.2)) = 0.01

        [Header(Multipliers)]
        _DensityMultiplier ("Density Multiplier", Float) = 1.0
        _ShadowStrength ("Shadow Strength", Float) = 1
        
        [Header(Lighting)]
        _Absorption ("Absorption", Range(0, 10)) = 0.5
        _Scattering ("Scattering", Range(0, 10)) = 0.5
        _Erosion ("Erosion", Range(0, 10)) = 0.5
        _ForwardPhaseConstant ("Forward Phase Function g", Range(0, 1)) = 0.4
        _BackwardPhaseConstant ("Backward Phase Function g", Range(-1, 0)) = -0.4
        _PhaseWeight ("Phase Weight", Range(0, 1)) = 0.5
        _ShadowThreshold ("Shadow Threshold", Range(0.01, 1)) = 0.1
        
        [Header(Textures (generated by SmokeManager script)]
        _VolumeTexture ("Volume Texture", 3D) = "" {}
        _NoiseTexture ("Noise Texture", 3D) = "" {}
    }
    SubShader
    {
        Tags
        {
            "RenderType"="Transparent"
            "Queue"="Transparent"
            "RenderPipeline" = "UniversalPipeline"
        }

        Pass
        {
            Name "VolumetricPass"
            Cull Front
            Blend SrcAlpha OneMinusSrcAlpha

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"


            struct Attributes {
                float4 positionOS : POSITION;
            };

            struct Varyings {
                float4 positionCS : SV_POSITION;
                float3 positionOS : TEXCOORD0;
                float3 positionWS : TEXCOORD1;
                float3 cameraOS : TEXCOORD2;
                float3 cameraWS : TEXCOORD3;
            };


            float4 _MainColor;

            Texture3D _VolumeTexture;
            SamplerState sampler_VolumeTexture;
            Texture3D _NoiseTexture;
            SamplerState sampler_NoiseTexture;
            
            float4 _WindDirection;

            float _StepSize;
            float _ShadowStepSize;

            float _DensityMultiplier;
            float _ShadowStrength;
            
            float _Absorption;
            float _Scattering;
            float _Erosion;
            float _ForwardPhaseConstant;
            float _BackwardPhaseConstant;
            float _PhaseWeight;
            
            float _ShadowThreshold;
            
            float density_multiplier;
            float shadow_strength;
            float sigma_a;
            float sigma_s;
            float sigma_t;

            // https://thebookofshaders.com/10/
            float Hash13(float3 n) {
                return frac(sin(dot(n, float3(393241, 196613, 98317))) * 43758.5453123);
            }
            
            float Hash11(float n) {
                return frac(sin(n) * 43758.5453123);
            }
            
            // https://en.wikipedia.org/wiki/Henyey%E2%80%93Greenstein_phase_function
            float Phase(float cosTheta, float g) {
                float numerator = 1 - g * g;
                float denominator = pow(1 + g * g - 2 * g * cosTheta, 1.5) * 4 * PI;
                return numerator / denominator;
            }

            // https://github.com/evanw/webgl-path-tracing/blob/master/webgl-path-tracing.js [98:109]
            bool AABBIntersection(float3 origin, float3 ray, float3 cubeMin, float3 cubeMax, out float tNear, out float tFar) {
                float3 tMin = (cubeMin - origin) / ray;
                float3 tMax = (cubeMax - origin) / ray;
                float3 t1 = min(tMin, tMax);
                float3 t2 = max(tMin, tMax);
                tNear = max(max(t1.x, t1.y), t1.z);
                tFar = min(min(t2.x, t2.y), t2.z);
                return tNear <= tFar && tFar > 0;
            }
            
            float LightRaymarch(float st_near, float st_far, float3 light_pos, float3 light_dir_os) {
                st_near = max(st_near, 0);
                
                float accumulated_shadow = 0;
                float shadow_distance_traveled = st_near;

                int shadow_steps = 20;
                
                [loop]
                for (int j = 0; j < shadow_steps; j++) {
                    if (shadow_distance_traveled >= st_far)
                        break;
                    if (accumulated_shadow >= _ShadowThreshold)
                        break;
                    
                    float3 shadow_pos = light_pos + (light_dir_os * shadow_distance_traveled);
                    float3 shadow_uv = shadow_pos + 0.5;

                    float shadow = _VolumeTexture.Sample(sampler_VolumeTexture, shadow_uv).r * _ShadowStepSize;
                    float3 shadow_noise = _NoiseTexture.Sample(sampler_NoiseTexture, shadow_uv + _WindDirection * _Time.x).rgb;
                    shadow *= shadow_noise.r;

                    if (shadow > 0) {
                        accumulated_shadow += shadow;
                    }

                    shadow_distance_traveled += _ShadowStepSize;
                }
                
                return accumulated_shadow;
            }
            
            float4 Raymarch(float3 ray_origin, float3 ray_dir, float3 light_dir_os, float3 light_color) {
                float3 box_min = float3(-0.5, -0.5, -0.5);
                float3 box_max = float3(0.5, 0.5, 0.5);
                float t_near, t_far;
                bool intersection = AABBIntersection(ray_origin, ray_dir, box_min, box_max, t_near, t_far);
                if (!intersection)
                    discard;

                t_near = max(t_near, 0);

                float distance_traveled = t_near;

                float accumulated_density = 0;
                float accumulated_transmittance = 1;
                float3 light_energy = 0;

                int max_steps = 100;

                [loop]
                for (int i = 0; i < max_steps; i++) {
                    if (distance_traveled >= t_far)
                        break;
                    if (accumulated_density >= 1)
                        break;

                    float3 current_pos = ray_origin + (ray_dir * distance_traveled);
                    float3 uv = current_pos + 0.5;

                    float density = _VolumeTexture.Sample(sampler_VolumeTexture, uv).r * _StepSize;
                    float3 noise = _NoiseTexture.Sample(sampler_NoiseTexture, uv + _WindDirection * _Time.x).rgb;
                    density *= noise.r;
                    density -= noise.g * density * _Erosion;
                    density = max(density, 0);

                    if (density > 0.001) {
                        accumulated_density += density;
                        
                        float3 light_pos = current_pos;
                        float st_near, st_far;
                        AABBIntersection(light_pos, light_dir_os, box_min, box_max, st_near, st_far);
                        
                        float phase_forward = Phase(dot(light_dir_os, ray_dir), _ForwardPhaseConstant);
                        float phase_backward = Phase(dot(light_dir_os, ray_dir), _BackwardPhaseConstant);
                        float phase = lerp(phase_forward, phase_backward, _PhaseWeight);
                        float shadow = LightRaymarch(st_near, st_far, light_pos, light_dir_os);
                        
                        
                        float transmittance = exp(-density * density_multiplier * sigma_t);
                        
                        float3 light_emitted = sigma_a * density * density_multiplier * _MainColor.rgb;
                        
                        float shadow_transmittance = exp(-shadow * shadow_strength * sigma_t);
                        float3 light_scattered = sigma_s * shadow_transmittance * phase * light_color;
                        
                        light_energy += accumulated_transmittance * transmittance * (light_scattered + light_emitted);
                        accumulated_transmittance *= transmittance;
                    }

                    distance_traveled += _StepSize;
                    distance_traveled += Hash13(current_pos) * _StepSize; // otherwise we get circle-like artifacts
                }
                
                return float4(light_energy, 1 - accumulated_transmittance);
            }

            Varyings vert(Attributes input) {
                Varyings output;

                VertexPositionInputs vertex_input = GetVertexPositionInputs(input.positionOS.xyz);
                output.positionCS = vertex_input.positionCS;
                output.positionOS = input.positionOS.xyz;
                output.positionWS = TransformObjectToWorld(output.positionOS);

                output.cameraWS = GetCameraPositionWS();
                output.cameraOS = TransformWorldToObject(output.cameraWS);

                return output;
            }

            half4 frag(Varyings input) : SV_Target {
                Light main_light = GetMainLight();
                float3 light_dir_ws = main_light.direction;
                float3 light_dir_os = normalize(TransformWorldToObjectDir(light_dir_ws));
                float3 light_color = main_light.color.rgb;
                
                density_multiplier = max(0, _DensityMultiplier);
                shadow_strength = max(0, _ShadowStrength);
                sigma_a = _Absorption;
                sigma_s = _Scattering;
                sigma_t = sigma_a + sigma_s;
                
                float3 ray_origin = input.cameraOS;
                float3 ray_dir = normalize(input.positionOS - ray_origin);

                float4 light = Raymarch(ray_origin, ray_dir, light_dir_os, light_color);

                return light;
            }
            ENDHLSL
        }
    }
}